name: go-jwt-auth-test
on: [push]

jobs:
  test-andpad-organization:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13.x', '1.14.x' ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          export GO111MODULE=on
          go mod download
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
      - name: Lint
        run: golangci-lint run
      - name: Test
        run: go test ./...
      - name: Build
        run: go build main.go
